### ISSUE TITLE
Smaller release file (remove not needed files from release)

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo-package#101]
I recently went through the process of trying to create a smaller package. Noticed some files could be removed that may not be needed in the release.

* Any `composer.json`, `composer.lock`, `bower.json` and `package.json`
* Any `changelog` or `changelog.md`, `ChangeLog.md` and `CHANGELOG.md` file. In theory could also delete readmes but if there is no license file in the package then the readme may contain the license info I suppose.
* any `Gruntfile.js` and `karma.conf.js`
* any travis yml
* any `phpunit.xml` and any `phpunit.xml.dist` and `.php_cs.dist`
* any `*.map` file. Would need to double check we're really only deleting JS Map files though. They won't work for debugging Matomo in the browser anyway since the map files don't resolve AFAIK because we're loading it from index.php and not from the actual source?
* There are a few commands that would not need to be available in a release like `plugins/CoreConsole/Commands/DevelopmentSyncProcessedSystemTests.php` as they are only available in dev mode. Since they can ping external servers it may be interesting to remove some dev commands.

* Should we eventually even remove the example plugins since they are only needed for development? I reckon that be good re file size but also we wouldn't want users to see them and having to think about what they are etc. Would also need to remove 2 example plugins from the `global.ini.php`.

There are in theory also many non-minimized JS files that could be removed and a lot jquery-ui files etc. Not sure we want to do this? That be in core though as we are committing those libraries.

**Comment by aureq** [comment]
I'm all for it. I think it's also possible to remove some demo files too. Maybe look at [Makefile:75](https://github.com/matomo-org/matomo-package/blob/9fe40b693f19450f8a9173e635c72802ac6a8209/Makefile#L75) onward. This is what I've been doing for the Debian package.

**Comment by mattab** [comment]
This looks mostly done so i will close it for now. if you can find more files that can be deleted from the release, let us know in a new issue :+1:
