### ISSUE TITLE
On upgrade "The Matomo JavaScript tracker file "/matomo.js" & "/piwik.js" is not writable"

### ISSUE THREAD

**Issue by nomandera** [matomo-org/matomo-package#109]
It occurs to me that on each upgrade on every install I receive this warning and manualy fix the issue using a copy and paste of the recommended commands.

Perhaps this is a job best done by the installer?

`
The Matomo JavaScript tracker file "/matomo.js" & "/piwik.js" is not writable which means other plugins cannot extend the JavaScript tracker. In the future even some core features might not work as expected. We recommend to make "/matomo.js" & "/piwik.js" writable by running this command: 
`
```
chmod +w /usr/share/matomo/matomo.js
chown www-data:www-data /usr/share/matomo/matomo.js

chmod +w /usr/share/matomo/piwik.js
chown www-data:www-data /usr/share/matomo/piwik.js
```

**Comment by aureq** [comment]
Hey @anoma, thank you for raising this issue and sharing some useful details. This is something that I should be able to fix in the upcoming release.

@mattab from a security perspective, it's making me uncomfortable and nervous knowing code is able to modify code that is served to end users. As a suggestion, I would recommend having a more secure way of serving customized content. Having core Matomo files as read-only is definitely a plus for security and our users.

**Comment by mattab** [comment]
@aureq 
> Having core Matomo files as read-only is definitely a plus for security and our users.

Thanks for the feedback, created this feature/docs request: https://github.com/matomo-org/matomo/issues/16060
