### ISSUE TITLE
Automate the packaging of Matomo beta/rc/stable releases via Github actions

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo-package#119]
To build a release we usually follow these steps:

* create new Github release (which automatically creates a tag)
* run `./scripts/build-package.sh 4.0.0-b3`
* the release is signed with my key so it asks for passphrase
* build finishes with success or error

Eventually, there's no way around it: we will need to automate the build of Matomo releases. It would be fantastic if this was completely automated for example via Github actions. I was thinking we could create a new repo for example `matomo-releases` or so, that only release managers would have access to (Matt, Thomas, Stefan, etc.). Then the Github actions would run in this repo and automate the steps above. We'd need to create a new public/private key pair to sign the build, that only release managers would have access to (and the Github action also). 

This would help a lot to let the team release versions without my involvement. And to save me some time. cc @tsteur @sgiehl

**Comment by sgiehl** [comment]
We could even fully automate that with a github action in the matomo repo. Whenever a tag (or github release) is created we could run the action to build the package. Upload the package to the build server and maybe even add it as release package to the version on github. 

If we want to limit that to specific people, we can check if the release was created by someone in a specified list or so...
But doing that in another repo would also be possible

**Comment by mattab** [comment]
fyi @sgiehl adding this to the current milestone, after our discussion

**Comment by tsteur** [comment]
@sgiehl ideally it would be triggered automatically when we tag a release in github? Not sure though if we can restrict who can tag a release or who can trigger a certain action?

Regarding upload to server SSH be likely better than FTP. Posting a release not sure unless it's super crazy secure which may be hard because then you suddenly need to think about brute force etc.

**Comment by tsteur** [comment]
Sounds good to use an action then so this way we can restrict it better. The action would create the tag then.

I created an account on our matomo server. You can connect using `ssh innocraft-staff-stefan@matomo.org` using your SSH key. Let me know if you need anything else 👍
