### ISSUE TITLE
Working on debian package generation: .eslintrc ?

### ISSUE THREAD

**Issue by e-gaulue** [matomo-org/matomo-package#138]
Running lintian on the package gives:
```
E: matomo: package-contains-eslint-config-file usr/share/matomo/node_modules/iframe-resizer/.eslintrc
E: matomo: package-contains-eslint-config-file usr/share/matomo/node_modules/ng-dialog/.eslintrc
```

Could those files be removed while generating the package (arround here https://github.com/matomo-org/matomo-package/blob/bde245f091256d74032e54ae51493f1364c315a5/scripts/build-package.sh#L379) or is there any reason to keep them, so I need to say lintian not to complain about?

Regards,

**Comment by sgiehl** [comment]
Tose files shouldn't be needed. Will push a fix.
