### ISSUE TITLE
Manifest / Integrity check has issues with symlinks

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo-package#145]
refs https://github.com/matomo-org/matomo/issues/18418

The file that caused issues was a symlink
![image](https://user-images.githubusercontent.com/273120/144299993-2e8742cf-580d-4fa2-92ca-762c413f037f.png)

Seems the manifest file is created only for files 
![image](https://user-images.githubusercontent.com/273120/144300051-a0e3c56e-affc-4782-91af-bb1907d5f5cb.png)

Aka any symlink will cause issues in the release as the integrity check would fail.

Also symlinks may cause issues on windows.

Should we maybe exit/error the build script if we find any symlink?

**Comment by sgiehl** [comment]
@tsteur what about simply adding something like this:
```bash
SYMLINKS=(`find ./ -type l`)
if [ ${#SYMLINKS[@]} -gt 0 ]
then
  echo 'Symlinks detected. Please check if following links should be removed:'
  echo ${SYMLINKS[*]}
  exit 1
fi
```

**Comment by tsteur** [comment]
Sounds good to me 👍 

We might also want to add a comment or better print in the message why that is (like issues with file integrity and windows etc) just so that not someone else later simply removes the check and so it's clear why symlinks won't work.
