### ISSUE TITLE
Plans for supporting piwik 2.x-LTS on Wheezy?

### ISSUE THREAD

**Issue by Patrick-Webscale** [matomo-org/matomo-package#46]
Hi Aurélien,

We are gratefully using your debian-apt-repository for installing Piwik on our servers.

As you may know, the 2.x-branch has been declared LTS, in anticipation to the new stable 3.x version of Piwik.
One of the requirements for Piwik3 is PHP5.6, which is NOT available in Debian Wheezy(oldstable).

What are your plans with the repository for debian.piwik.org?
Will you build and host the packages for both the 2.x-lts and 3.x-stable Piwik-releases?
Do you have plans to keep supporting Wheezy(oldstable), or drop support and only support Jessie(stable)?

We sincerely hope you will keep supporting Wheezy and Piwik 2.x-lts.
I know this will require some reorganisation to the apt-repository, something like dotdeb would be nice: https://packages.dotdeb.org/dists/

Many thanks in advance!

**Comment by aureq** [comment]
@Patrick-Webscale technically that should be doable but @mattab is the project lead and the decision is his.

**Comment by mattab** [comment]
Hi @aureq @Patrick-Webscale - we will want the debian repositories to support both Piwik 2.X and Piwik 3.X. We still have at least 9 months before we will release 3.0.0 stable so it gives us time @aureq to make the change. Is there any particular challenge in supporting the LTS and 3.0 at the same time?

**Comment by mattab** [comment]
Since it's extra work and maybe @aureq you don't have time, we can close this issue as "wont fix". It's Ok to "push" users to 3.0.0 since upgrade is safe and well tested

**Comment by aureq** [comment]
Hi @mattab I think it still would be a nice feature to have. Just the same way I'd like to have the beta versions published in the repository too.

I was initially thinking of numbering package names (piwik-2.17.1-1, piwik-3.0.0-1 piwik4-...) but I'm not sure if that's a good idea.
As a possible alternative, it could be possible to publish multiple distributions inside the same repository. At the moment, we only have `stable`, but we could create new ones (`lts`, `stable`, `unstable`) and in which the package name would remain the same (piwik-x.y.z-a).

This would allow us to control which distribution receives specific piwik versions while retaining a unique package name (`piwik`). It would also become explicit for users to know on which branch they are on.

Thoughts?

**Comment by mattab** [comment]
>  it could be possible to publish multiple distributions inside the same repository. At the moment, we only have stable, but we could create new ones (lts, stable, unstable) 

Sounds good, as it seems to be consistent with Debian packaging technique, and it's useful to keep only one package name `piwik` :+1:

**Comment by aureq** [comment]
I'm closing this issue as `Wheezy` is no longer supported by Debian or via the LTS effort. It's now `Jessie`.
`piwik-2` is no longer maintained either, nor is `php-5x`, so resolving this issue.
