### ISSUE TITLE
piwik blog block does not work

### ISSUE THREAD

**Issue by sblondon** [matomo-org/matomo-package#66]
By default, the community debian package displays a block for the blog from piwik.org. However, piwik.org redirect to matomo.org, so the block should be removed or updated.

Screenshot:
![piwik_blog_error](https://user-images.githubusercontent.com/1708780/40372362-c9a157d4-5de4-11e8-9225-81d0ba31772d.png)

The issue is not really important because users can close the block.

**Comment by aureq** [comment]
I don't think this is specific to Debian/Ubuntu package, but maybe a left over in Matomo code?

@sblondon Could you give a few steps to reproduce the issue?
@mattab Could you please have a look into this?

Thanks

**Comment by sblondon** [comment]
I installed the debian package provided by matomo on debian 9. The blog plugin is displayed by default.

```$ apt show matomo
Package: matomo
Version: 3.5.1-1
Priority: optional
Section: web
Maintainer: Aurelien Requiem <aurelien@requiem.fr>
Installed-Size: 52.5 MB
Pre-Depends: debconf (>= 0.5.00) | debconf-2.0
Depends: php5-cli (>= 5.5.9) | php-cli, php5-mysql | php5-mysqlnd | php-mysql, php5-curl | php-curl, php5-gd | php-gd
Recommends: logrotate, libapache2-mod-php5 (>= 5.3.3) | php5-cgi (>= 5.5.9) | php5-fpm (>= 5.5.9) | libapache2-mod-php | php-cgi | php-fpm, php5-geoip | php-geoip
Suggests: mariadb-server | mysql-server, geoip-database-extra, php-mbstring
Homepage: http://matomo.org
Download-Size: 11.8 MB
APT-Manual-Installed: no
APT-Sources: https://debian.piwik.org piwik/main amd64 Packages
Description: Leading Free/Libre open source Web Analytics software
 Matomo (formerly Piwik) is a full featured PHP MySQL software program that
 you download and install on your own webserver. At the end of the five minute
 installation process you will be given a JavaScript code. Simply copy and
 paste this tag on websites you wish to track and access your analytics reports
 in real time.
```

**Comment by sblondon** [comment]
Sorry, the previous message is the current version installed on the server but it has been updated since the installation. So the previous answer is wrong: perhaps it's fixed in the current version.
The package with the bug was piwik v.3.2.1-1.

In case it helps, the package infos from /var/logs/apt/history.1.log:
```
Start-Date: 2018-05-17  12:02:53
Commandline: apt-get install piwik
Requested-By: stephane (1002)
Install: libwebp6:amd64 (0.5.2-1, automatic), php7.0-cli:amd64 (7.0.27-0+deb9u1, automatic), php-common:amd64 (1:49, automatic), php7.0-gd:amd64 (7.0.27-0+deb9u1, automatic), libgd3:amd64 (2.2.4-2+deb9u2, automatic), php7.0-opcache:amd64 (7.0.27-0+deb9u1, automatic), php7.0-common:amd64 (7.0.27-0+deb9u1, automatic), libtiff5:amd64 (4.0.8-2+deb9u2, automatic), php7.0-json:amd64 (7.0.27-0+deb9u1, automatic), psmisc:amd64 (22.21-2.1+b2, automatic), php7.0-readline:amd64 (7.0.27-0+deb9u1, automatic), php7.0-curl:amd64 (7.0.27-0+deb9u1, automatic), php-geoip:amd64 (1.1.1-1, automatic), piwik:amd64 (3.2.1-1), libjbig0:amd64 (2.1-3.1+b2, automatic), libxpm4:amd64 (1:3.5.12-1, automatic), libapache2-mod-php7.0:amd64 (7.0.27-0+deb9u1, automatic), libjpeg62-turbo:amd64 (1:1.5.1-2, automatic), php7.0-mysql:amd64 (7.0.27-0+deb9u1, automatic)
```

**Comment by aureq** [comment]
@sblondon have you upgraded to the latest version? Is this problem still ocuring?

**Comment by sblondon** [comment]
The current version installed is 3.5.1-2 on the server. I removed previously the plugin to don't have the error displayed.

I tried to add the updated plugin via the dashboard button (All the gadget > About Matomo > Matomo.org Blog), however it doesn't load: it's blocked on previsualisation.

It seems the problem is due to a 500 error when loading http://matomo.private-data.tld/index.php?date=yesterday&module=RssWidget&action=rssPiwik&widget=1&idSite=1&period=day

The content of the 500 error page is:
```A fatal error occurred
The following error just broke Matomo (v3.5.1):

Call to undefined function Piwik\Plugins\RssWidget\simplexml_load_string()
in

/usr/share/matomo/plugins/RssWidget/RssRenderer.php line 47
Troubleshooting
Follow these steps to solve the issue or report it to the team:
If you have just updated Matomo to the latest version, please try to restart your web server. This will clear the PHP opcache which may solve the problem.
If this is the first time you see this error, please try refresh the page.
If this error continues to happen, we appreciate if you send the error report to the Matomo team.
Further troubleshooting
If this error continues to happen, you may be able to fix this issue by disabling one or more of the Third-Party plugins. If you don't know which plugin is causing this error, we recommend to first disable any plugin not created by "Matomo" and not created by "InnoCraft". You can enable plugin again afterwards in the Plugins or Themes page under settings at any time.
```

Restarting Apache2 does not fix the 500 error.

**Comment by aureq** [comment]
@sblondon Well, the error is here. The additional plugin you installed (`RssWidget`) requires `simplexml` which is outside of Matomo requirements. Debian/Ubuntu should have it: `apt-get install php-simplexml -V` and then restart the web server (might not even be necessary).

**Comment by sblondon** [comment]
Installing `php-simplexml` fixes the issue. The Matomo blog plugin works properly. So the original issue is solved.

Searching in the motomo source code, there are several occurences of the `simplexml_load_string()` function so this error could occur in other cases (especially Zend and the Alexa plugin).

https://github.com/matomo-org/matomo/search?q=simplexml_load_string&unscoped_q=simplexml_load_string

I think `php-simplexml` should be added to the dependencies. I don't provide a patch to avoid conflict with the other PR about the `php-mbstring` dependency I made yesterday with the help of a Debian Developer (#70).
