### ISSUE TITLE
cache git clone

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo-package#71]
Since https://github.com/matomo-org/matomo-package/commit/9f16d4434c7b7b45833e610850c1a49830ba8181 every build runs in a separate directory. 
Because of this multiple builds after each other will need to download the complete repo from scratch.

It suggest to copy the repository to another global directory at the end of the build and copy it back before the clone. That way the download should be a lot quicker.

@aureq What do you think?

**Comment by mattab** [comment]
Sounds good @Findus23 - it's really important we get a fast package script again (currently taking like 30min or more to package).

**Comment by Findus23** [comment]
I guess nearly all of the 30min are downloads as on my server all steps until the zip generation take about 3 minutes.

**Comment by aureq** [comment]
@Findus23 Thanks for the work. I'll be on holidays next week so I'll have more time to look into this.
