### ISSUE TITLE
autoload.php files don't get deleted, but ignored from integrity checker

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo-package#77]
The following line excludes `manifest.inc.php|autoload.php|autoload_real.php` files from the manifest.inc.php even when they don't get deleted. This causes the integrity checker to warn (see https://github.com/matomo-org/matomo/issues/13364 and https://github.com/matomo-org/matomo/issues/13318)

https://github.com/matomo-org/matomo-package/blob/11c5f9c8dea2b9079daf9300547fb0dd1061957b/scripts/build-package.sh#L271

This didn't happen before, because only in 3.6.0 I added sparklines which has an autoload.php file and @sgiehl added an autoload.php to DeviceDetector in https://github.com/matomo-org/device-detector/pull/5742

@mattab, @tsteur Is there a reason for this line?

**Comment by sgiehl** [comment]
FYI. I will remove the autoload.php from device detector for upcoming composer packages again. Doesn't make sense to have it in this case, as composer handles the autoloading...

**Comment by mattab** [comment]
>  Is there a reason for this line?

The reason we excluded them from manifest is because IIRC the files contain some random hash that changes depending on the server or so, so the manifest was failing.

**Comment by mattab** [comment]
So actually we could fix the package script and only specifically grep out  'vendor/autoload.php' and         'vendor/composer/autoload_real.php' and leave any other 'autoload.php' in the manifest file.

**Comment by mattab** [comment]
fixed in https://github.com/matomo-org/matomo-package/commit/2a683a8df5e7a50ab12461e433a14a481c4e6cf1
