### ISSUE TITLE
Problem loading MaxMind geoloc database

### ISSUE THREAD

**Issue by ma2thieu** [matomo-org/matomo-package#83]
When I try downloading the Maxmind geoloc database from Matomo admin panel I get a lot of these messages and the database doesn't download : 
```
WARNING: /usr/share/matomo/core/Http.php(790): Warning - fclose() expects parameter 1 to be resource, boolean given - Matomo 3.5.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
```
Changing ownership of `/usr/share/matomo/misc` to user `www-data` fixes the problem.
```
drwxr-xr-x  9 www-data www-data 4.0K Sep 16 18:11 misc
```

**Comment by aureq** [comment]
@ma2thieu This is ok as a workaround, but the web server shouldn't have write permissions in `/usr/share/matomo` for security reasons.

Could you please open an issue with matomo directly requesting that the MaxMind database is saved in `tmp/` instead. This would be a much better outcome.

Thanks

**Comment by aureq** [comment]
@mattab I think it would be great if our team could look into this please? Since our Debian/Ubuntu package is installed system wide, the web server shouldn't be allowed to write in `/usr/share/matomo/misc`. Instead the geoloc database should be written in `/usr/share/matomo/tmp`.

**Comment by mattab** [comment]
@aureq Just checked and currently it is not possible to change the path where the GeoIP database is stored (it has to be in `misc/` folder). Created an issue here for now: https://github.com/matomo-org/matomo/issues/13770 This should be fixed in the next few months (but not next few days/weeks) :+1:

**Comment by mattab** [comment]
Thanks for your patience, let's continue the discussion in this other issue for now, where we're looking for a new maintainer for the debian package: #131
