### ISSUE TITLE
Debian package for Matomo is missing for Debian/Ubuntu

### ISSUE THREAD

**Issue by aureq** [matomo-org/matomo-package#88]
This is a generic issue to track down each time a new release is pushed into the official package repository.

**Comment by aureq** [comment]
version `3.8.0-1` has been published
version `3.8.1-1` has been published

**Comment by elukey** [comment]
Any news for 3.9.1? Asking since I noticed some security fixes :)

**Comment by elukey** [comment]
Any news? 3.9.1 seems listing some security upgrades, it would be great to deploy the fix asap :)

**Comment by aureq** [comment]
version `3.9.0-1` has been published
version `3.9.1-2` has been published

**Comment by bill-mcgonigle** [comment]
Hi, there.  Don't mean to be a nudge, but we're three weeks out from the last  "critical" security update.

**Comment by anoma** [comment]
If it wasn't a security release I would not +1 or pollute the thread but `Matomo 3.11.0 July 23, 2019` is tagged as a critical security release and as off this post is public for 36 days.

**Comment by aureq** [comment]
@mattab I recently left AWS and so I lost to my VMs and especially the one to build Matomo for Debian. Do you have a build environment you could provide somehow ?

Cheers

**Comment by mattab** [comment]
@aureq For sure, I have a fully isolated environment where you can SSH into and run anything you want. I'll reach out by email. Thanks,

**Comment by pedro-nonfree** [comment]
@mattab @aureq any progress? Thanks!

**Comment by aureq** [comment]
version `3.11.0-1` has been published
version `3.11.0-2` has been published

If you are using GeoIP2, then you may want to also install `libmaxminddb0`. See #96

**Comment by aureq** [comment]
version `3.12.0-1` has been published.

**Comment by anoma** [comment]
User feedback

version `3.13.2-1`  has been published.

and not tracked here (in case other like me bookmark this ticket for release notices)

**Comment by aureq** [comment]
Hi @anoma 

It's actually been pushed. https://github.com/matomo-org/matomo-package/commit/d9570a0692e370c742fc1ee5a5229b1dbb087da0

**Comment by aureq** [comment]
To all,

It's not really practical to announce every single `.deb` here. There's a few things that need to happen but you should know that I'd like to:
* fully automate the CI/CD from the point a new release is published on the matomo repository
* automatically publish the `.deb` into the package repository
* update the `Releases` tab of this repository so anyone could subscribe and get notified via GH notification system
