### ISSUE TITLE
Failed upgrade, possible mariadb availability race

### ISSUE THREAD

**Issue by nomandera** [matomo-org/matomo-package#90]
I suspect this failed upgrade was due to mariadb not being fully available/ready as it was also being upgraded. within the same apt session

  Please wait while Matomo is upgrading...
                                            
```
  [Zend_Db_Adapter_Exception]               
  SQLSTATE[HY000] [2002] Connection refused  
                                            
  [PDOException]                            
  SQLSTATE[HY000] [2002] Connection refused                                            

core:update [--yes]

dpkg: error processing package matomo (--configure):
 subprocess installed post-installation script returned error exit status 255
```

A subsequent attempt following this fail resulted in:

```
Matomo has been successfully updated!

W: APT had planned for dpkg to do more than it reported back (0 vs 4).
```

Since this was a test VM i reverted to pre-upgrade snapshot, upgraded mariadb , waiting an arbitrary settling in period, unheld and immediately patched Matomo with no issues.

Ultimately the fix was simple (in retrospect) but ideally the process should be more robust. Apologies if I missed any documentation that details this or issue or process.

Edit: Debian 9.6, Matomo 3.6.1 upgrade

**Comment by mattab** [comment]
Thanks for your patience, let's continue the discussion in this other issue for now, where we're looking for a new maintainer for the debian package: #131
