### ISSUE TITLE
libmaxminddb recommendations

### ISSUE THREAD

**Issue by nomandera** [matomo-org/matomo-package#96]
Matomo [FAQ 163](https://matomo.org/faq/how-to/#faq_163 ) recommends manual git or tarball install of libmaxminddb.

Whilst not as up to date Debian do ship libmaxminddb and it is freely available from [here](https://packages.debian.org/search?keywords=libmaxminddb&searchon=names&suite=stable&section=all)

Given this would the recommendation for [matomo-package](https://github.com/matomo-org/matomo-package) be to follow apt like the rest of the install or break with this and follow the FAQ, updating by hand for ever more.

Can/should we ship it by default or as a recommended package?

For reference the changelog can be found [here](https://github.com/maxmind/libmaxminddb/releases). It is far from fast paced.

**Comment by aureq** [comment]
Hi @anoma 

Yes, this is an excellent suggestion. I'll add the dependency as `Suggests` instead of `Recommends`.
This will give the necessary information for people to decide whether or not they want to install that extra package without changing anything on users who already performed an earlier install.

**Comment by aureq** [comment]
@mattab Could you please add the above to the official installation documentation?
I just released `3.11.0-2` and it has `libmaxminddb0` as a suggested dependency.

**Comment by mattab** [comment]
@aureq I'm not sure where to update the doc? we don't really have a doc specific to Debian. Also by default for all users Matomo should work without this new dependency (as there is a way in the UI to easily download the geolocation DB from maxmind servers and activate the PHP geolocation module. it takes a few manual steps.)

Where would you add the sentence eg. `If you run a Debian or Ubuntu server, you can install the Maxmind geolocation database in your system in your system by running 'apt install libmaxminddb0'`

**Comment by anoma** [comment]
There is quite a delay between Debian and source versions as recommended in the official documentation.

For example as of today

Debian (678 days ago)
https://github.com/maxmind/libmaxminddb/releases/tag/1.3.2

Upstream (24 days ago)
https://github.com/maxmind/libmaxminddb/releases/tag/1.4.2

Perhaps, license permitting, we should publish a deb to the Matomo repo?

**Comment by aureq** [comment]
@anoma I don't think this is wise to publish our own package for `libmaxminddb` as it could conflict with the one installed by the distribution. Debian favors security and stability over the latest version of a library or an application. This is done to ensure compatibility and stability across their ecosystem of applications that rely on the dependencies. (See version `1.4.0`/`1.4.1` as unfortunate examples).

@mattab If we want to include this sentence in our documentation, I would put that in the prerequisite section but I would make it clear this is optional. This way, system administrators would know they could optionally install the dependence.

**Comment by mattab** [comment]
@aureq could we maybe add this instruction to the debian package installer at https://debian.matomo.org/ ? or directly include the sudo apt-get install for this package within the debian package?

**Comment by aureq** [comment]
Hi @anoma 

So, I've been looking into this issue and I don't see where `libmaxminddb` fits into this picture. The package `php-geoip` seems to work fine for me. However, it requires a but of configuration if you wish to include additional databases like you mentioned earlier.

The PHP module has one directive that can override the default (defined a compilation) database path [`geoip.custom_directory`](https://www.php.net/manual/en/geoip.configuration.php). This goes either in your `php.ini` or in Debian `/etc/php/(php_version)/mods-available/geoip.ini` (Make sure the module is enabled though - `phpenmod`).

@mattab [FAQ 163](https://matomo.org/faq/how-to/#faq_163) mentions `libmaxminddb`, but I don't have installed on my Debian. Do you have any references? When I look at Matomo admin console, the GeoIP PECL extension seems to be enough to make Matomo happy. This extension is installed via `php-geoip` which is already included in the recommended packages. Unless an administrator installs Matomo with `apt-get install matomo --no-install-recommends`, the `php-geoip` package is automatically installed.

### Next actions
* @anoma : Could you please look at Matomo admin console after installing and enabling `php-geoip` please? Feel free to provide any additional information on the other GeoIP databases using the module runtime configuration.
* @mattab : Could you please provide information on the FAQ 163 mentioned and the MaxMind library dependency.

Thanks

**Comment by mattab** [comment]
@aureq We're actually going to probably stop using Maxmind in Matomo very soon as they're changing their terms and conditions, see discussion in https://github.com/matomo-org/matomo/issues/15308 so I propose we stop working on this until a decision is taken in that issue. (we'll probably work with a new geolocation provider soon)

**Comment by aureq** [comment]
@mattab Thank you for the heads-up.

**Comment by sgiehl** [comment]
If we add support for DB-IP, libmaxminddb should still be recommended, as it should work with their dbs as well

**Comment by rroblik** [comment]
Please where to put db-ip files ?
Examples (not working) : 

``` 
/var/www/misc/dbip-city-lite-2020-02.mmdb
dbip-country-lite-2020-02.mmdb 
``` 

Best regards

**Comment by sgiehl** [comment]
it needs to be placed within the misc directory in matomo

**Comment by rroblik** [comment]
Which path please?

**Comment by sgiehl** [comment]
whereever you have placed your matomo install 🤷‍♂ 
something like `/path/to/matomo/misc`

**Comment by rroblik** [comment]
Does the filename is important ?
because not working
![image](https://user-images.githubusercontent.com/5805093/73658646-fa7fb900-4694-11ea-9cc7-7695a836fad1.png)

![image](https://user-images.githubusercontent.com/5805093/73658669-079ca800-4695-11ea-9668-f09567c63d13.png)

**Comment by sgiehl** [comment]
So your matomo is installed directly within /var/www ?

**Comment by rroblik** [comment]
Yes (docker)

**Comment by rroblik** [comment]
EDIT : name mater !
Once renamed to 

```
/var/www/misc/GeoLite2-City.mmdb
/var/www/misc/GeoLite2-Country.mmdb 
```

It's working (using `GeoIP 2` core plugin)

**Comment by sgiehl** [comment]
That depends on the Matomo version you are using. The latest release should also handle the dbip files

**Comment by robertoschwald** [comment]
I wished the needed manual download / rename I would have found in the FAQ. It took some time how to figure out how to switch from GeoIP1 to GeoIP2 with DBIP. WIth the info from @rroblik it works here as well now. Thanks for that.

**Comment by mattab** [comment]
Thanks for your patience, let's continue the discussion in this other issue for now, where we're looking for a new maintainer for the debian package: #131
