### ISSUE TITLE
Debian stretch (Matomo will stop supporting PHP 7.0 in the next major version.)

### ISSUE THREAD

**Issue by anoma** [matomo-org/matomo-package#99]
Matomo 3.10.0 is warning

```
Warning
Matomo will stop supporting PHP 7.0 in the next major version.
Upgrade your PHP to at least PHP 7.1, before it's too late!
The PHP version 7.0 you are using has reached its End of Life (EOL).
You are strongly urged to upgrade to a current version, as using this version 
may expose you to security vulnerabilities and bugs that have been fixed in 
more recent versions of PHP.
```

however this package is currently installing

```
# php -v
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies
```

on Debian stretch

```
# cat /etc/debian_version 
9.9
```

Given the pace of Debian it may be prudent to get ahead of this one so that if the timings dont match we cater for it and at the very least dont break the install.

**Comment by Findus23** [comment]
Thankfully Debian Buster (10) came out a few days ago and comes with PHP 7.3 by default. So until Matomo 4 will be released (which is quite some time in the future) you will have more than enough time to upgrade to the current Debian stable.

**Comment by anoma** [comment]
Agree but there is a reasonable chance that between now and 2022 there will be a period where Stretch is still supported, the Debian security team is backporting fixes for 7.0 and Matomo 4.X is out and no longer supported on the OS by virtue of the EOL php version.

Regardless this giant warning is going to look awful if we are stuck with it potentially for years.

It may be in this projects interest to start discussions on deprecating Stretch on a timeline independent of Debian themselves to save what will inevitably be a royal headache of maintaining 2 branches for potentially more than a year.

**Comment by aureq** [comment]
@Findus23 Could you also confirm this is still current please ? https://matomo.org/docs/requirements/
Especially that PHP 5.9.9 is a minimum requirement.

**Comment by Findus23** [comment]
@aureq Yes all Matomo 3.x versions will continue to support PHP 5.5.9 and above

But once Matomo 4 comes out (which isn't in the near feature, but development will start soon) it will only support PHP 7.1+

You can find more details about this here: https://github.com/matomo-org/matomo/issues/13611

**Comment by anoma** [comment]
This is good news.

The warning added to Matomo 3.10.0 is very useful as it allows me to plan ahead but it is quite intrusive if it is going to be present from now on.

**Comment by anoma** [comment]
Is there any way to silence this warning in the interim it is quite intrusive and only really relevant to Debian stable when a new OS is released.

**Comment by aureq** [comment]
@mattab I believe the warning is created by the matomo application itself. Is there a workaround?

**Comment by Findus23** [comment]
@anoma 
You could (until you got around to upgrading), change the version here to your PHP version.

https://github.com/matomo-org/matomo/blob/45dd3a9e5c6513f48ed55b51ecda185fb4bdf837/core/Plugin/ControllerAdmin.php#L215

**Comment by anoma** [comment]
We now have a second PHP warning and this one, at least the way it is worded, appears critical.

```
You must upgrade your PHP version in order to receive the latest Matomo update.
Matomo cannot be upgraded to the latest major version because your PHP version is too old. Please upgrade your PHP version to at least PHP 7.2 so your Matomo analytics data stays secure.
```
![PHP warnings](https://i.imgur.com/vopOzTf.jpg)

I have successfully upgraded to Matomo 3.13.5 but it would appear this would be the last one?

Obviously this is a very big deal as it is essentially EOL Debian Stretch more than two full years early and taking it away from being a viable install platform for new users.

Can we find out definitively how long we have cause being selfish for a minute this is going to be a major headache justifying.

**Comment by sgiehl** [comment]
@anoma Matomo 3 will likely get another one or two regular releases before Matomo 4 will be released. After Matomo 4 release Matomo 3 will likely receive only critical bug fixes and security fixes while in LTS (https://github.com/matomo-org/matomo/issues/15920)

**Comment by anoma** [comment]
@sgiehl thanks for the excellent information. This helps me a lot although it still leaves a lot to discuss here in terms of how we handle this project. 

Perhaps it is time to start thinking about pinning php or using a third-party repository (as seems to be the most common solution from google).

If we dont then in a couple of versions installs will start failing.

**Comment by anoma** [comment]
I am getting a little worried we are not actively formulating a plan for this landmark event.

As I understand it within a few months Matomo 3 will be demoted to non feature critical fixes only which is in all practical ways an EOL notice for this project as it currently is deployed.

We also do not know, but can likely safely assume, plugins will be in the same boat and perhaps 3rd party may EOL even sooner.

I would suggest that the path of least resistance would be:

-  in advance of this happening we release a notice for this project on the implications of what it all means and include options to upgrade PHP. This will silence the horrible GUI warnings, ensure we maximize the life of version 3 and pave the way for version 4.
- We discuss what to do to allow users here to migrate from version 3 to version 4
- We set an EOL date here for version 3 which may be less than Matomo upstream otherwise we will be committing to the maximum effort solution of supporting both for as long as possible (there will always be hold outs)

**Comment by mattab** [comment]
FYI Matomo 4.0.0 which will be released in the next 48 hours will support PHP 7.2.5 or greater.

**Comment by anoma** [comment]
Thanks for the update. Obviously this has implications for anyone using Debian 9 LTS which whilst still well within support:

`Debian 9 will also receive Long Term Support for five years after its initial release with support ending on June 30, 2022`

Checking specifics today 23-11-2020:

```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
php -v
PHP 7.0.33-0+deb9u10 (cli) (built: Oct  6 2020 17:08:28) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u10, Copyright (c) 1999-2017, by Zend Technologies
```
It would appear this OS is no longer capable of supporting Matomo.

The immediate issue is how this will be handled for new installs but I would appreciate it if I could get some feedback on what we should do for upgrades. Obviously we can pin or maybe even backport but if that isnt officially supported this will require an unplanned OS update which is considerably more "expensive" in terms of time.

**Comment by Findus23** [comment]
Keep in mind that there is also a LongTermSupport for Matomo 3, so there is still a bit time left for the update:
https://matomo.org/blog/2016/01/announcing-long-term-support-in-matomo-the-analytics-platform-for-your-mission-critical-projects/

**Comment by anoma** [comment]
Cherry picked the relevant line:

_

> How long will a major version be supported?
> 
> Any major version will be supported for at least 12 months after the initial release of the next major release. For example, if in November 2020 Matomo 4.0 was released, then Matomo 3.X will be supported at least up to November 2021.


_

This is very useful and delays the problem but there will still be 6 months where Debian 9 will be within LTS support and Matomo 3 wont.

I doubt we can drop Debian LTS new installs or tell people for a whole year they cant install Matomo 4 on Debian so we just need to find a way Matomo are happy supporting for backporting a newer php. There are many options all with pros and cons.

The right time to deal with this investigation is now though

**Comment by anoma** [comment]
Closing. Thread superseded by https://github.com/matomo-org/matomo-package/issues/122
